blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://mcp-scanner.readthedocs.io
    about: Check the documentation for usage guides and API reference
  - name: Security Advisory
    url: https://github.com/example/mcp-scanner/security/advisories
    about: Report security vulnerabilities privately
  - name: Discussions
    url: https://github.com/example/mcp-scanner/discussions
    about: Ask questions and discuss features with the community